/* Generated by Convex. Run `npx convex dev` to regenerate. */
/** Stub: use `any` so hooks accept our manual refs; real codegen gives full types. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export declare const api: any;
