/* Generated by Convex. Run `npx convex dev` to regenerate. */

const FUNCTION_NAME = Symbol.for("functionName");

function ref(name) {
  return { [FUNCTION_NAME]: name };
}

export const api = {
  participants: {
    list: ref("participants:list"),
    seed: ref("participants:seed"),
    findByName: ref("participants:findByName"),
    getByStringId: ref("participants:getByStringId"),
  },
  scheduleRows: {
    saveForParticipant: ref("scheduleRows:saveForParticipant"),
    getForParticipant: ref("scheduleRows:getForParticipant"),
    getAllForCohort: ref("scheduleRows:getAllForCohort"),
    getCoursesWithParticipants: ref("scheduleRows:getCoursesWithParticipants"),
  },
  actions: {
    extractScheduleFromImage: ref("actions:extractScheduleFromImage"),
    getBestMeetingTimes: ref("actions:getBestMeetingTimes"),
  },
};
