/* Generated by Convex. Run `npx convex dev` to regenerate. */
import type { GenericId } from "convex/values";

export type DataModel = {
  participants: { id: string; name: string; major: string; gender: string; birthday: string; phone: string };
  scheduleRows: {
    participantId: GenericId<"participants">;
    subject: string;
    number: string;
    days: string;
    start: string;
    duration: number;
    lab?: string;
    labDays?: string;
    labStart?: string;
    labDuration?: number;
  };
};
