/* Generated by Convex. Run `npx convex dev` to regenerate. */
"use strict";
const { queryGeneric, mutationGeneric, actionGeneric } = require("convex/server");
module.exports = {
  query: queryGeneric,
  mutation: mutationGeneric,
  action: actionGeneric,
};
