/* Generated by Convex. Run `npx convex dev` to regenerate. */
import type { DataModel } from "./dataModel";
import type { GenericMutationCtx, GenericQueryCtx, GenericActionCtx } from "convex/server";
import type { GenericQueryCtx, GenericMutationCtx, GenericActionCtx } from "convex/server";

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;
export type DatabaseReader = QueryCtx["db"];
export type DatabaseWriter = MutationCtx["db"];

export declare const query: import("convex/server").QueryBuilder<DataModel, "query">;
export declare const mutation: import("convex/server").MutationBuilder<DataModel, "mutation">;
export declare const action: import("convex/server").ActionBuilder<DataModel, "action">;
