/** Texas A&M course subject codes (4–5 letter) → department name. */
export type TamuSubjectCode = keyof typeof TAMU_SUBJECTS;

export type TamuSubject = {
  code: TamuSubjectCode;
  name: string;
};

export const TAMU_SUBJECTS = {
  ACCT: "Accounting",
  AEGD: "Adv Ed Gen Dentistry",
  AERO: "Aerospace Engineering",
  AERS: "Aerospace Studies",
  AFST: "Africana Studies",
  AGCJ: "Ag Comm & Journalism",
  AGEC: "Agricultural Economics",
  AGLS: "Ag & Life Sciences",
  AGSM: "Agricultrl Systems Mgmt",
  ALEC: "Ag Leadrshp, Ed & Comm",
  ALED: "Ag Leadership & Dev",
  ANLY: "Analytics",
  ANSC: "Animal Science",
  ANTH: "Anthropology",
  ARAB: "Arabic",
  ARCH: "Architecture",
  AREN: "Architectural Engr",
  ARSC: "Arts & Sciences",
  ARTS: "Art",
  ASCC: "Academic Success Center",
  ASIA: "Asian Studies",
  ASTR: "Astronomy",
  ATMO: "Atmospheric Sciences",
  ATTR: "Athletic Training",
  BAEN: "Biological & Ag Engr",
  BEFB: "Bilingual Ed Field Based",
  BESC: "Bioenvironmental Sci",
  BESL: "Bilingual ESL Education",
  BICH: "Biochemistry",
  BIMS: "Biomedical Science",
  BIOL: "Biology",
  BIOT: "Biotechnology",
  BMEN: "Biomedical Engineering",
  BUAD: "Business Administration",
  BUSH: "Geo. Bush School of Gov",
  BUSN: "Mays Business School",
  CARC: "College of Architecture",
  CEHD: "Coll of Ed & Human Dev",
  CHEM: "Chemistry",
  CHEN: "Chemical Engineering",
  CHIN: "Chinese",
  CLAS: "Classics",
  CLAT: "College of Arts & Sci",
  CLEN: "College of Engineering",
  COMM: "Communication",
  COSC: "Construction Science",
  CPSY: "Counseling Psychology",
  CSCE: "Computer Sci & Engr",
  CULN: "Culinology",
  CVEN: "Civil Engineering",
  DAEN: "Data Engineering",
  DCED: "Dance Education",
  DDHS: "Dental Hygiene",
  DHUM: "Digital Humanities",
  DPHS: "Dental Public Health",
  ECCB: "Eco & Conservation Biol",
  ECDE: "Early Chldhd Devl & Educ",
  ECEN: "Electrical & Comp Engr",
  ECMT: "Econometrics",
  ECON: "Economics",
  EDAD: "Educational Admin",
  EDCI: "Educ Curriculum & Dev",
  EDHP: "Ed Healthcare Prof",
  EEBL: "Ecology & Evol Biology",
  EHRD: "Ed Human Res Develop",
  ENDG: "Engr Design Graphics",
  ENDO: "Endodontics",
  ENDS: "Environmental Design",
  ENGL: "English",
  ENGR: "Engineering",
  ENGY: "Energy",
  ENSS: "Envion Systems Science",
  ENTC: "Engineering Technology",
  ENTO: "Entomology",
  ENTR: "Entrepreneurship",
  EPFB: "Educ Psyc Field Based",
  EPSY: "Educational Psychology",
  ESET: "Electronic Sys Eng Tech",
  ESST: "Envir & Sustain Studies",
  EURO: "European Studies",
  EVEN: "Environmental Engr",
  FILM: "Film Studies",
  FINC: "Finance",
  FINP: "Financial Planning",
  FIVS: "Forensic & Inv Science",
  FORS: "Forensic Healthcare",
  FREN: "French",
  FSTC: "Food Science & Tech",
  FYEX: "First Year Experience",
  GENE: "Genetics",
  GEOG: "Geography",
  GEOL: "Geology",
  GEOP: "Geophysics",
  GEOS: "Geosciences",
  GERM: "German",
  GLST: "Global Studies",
  HBEH: "Health Behavior",
  HCPI: "Healthcare Prof Core In",
  HDFS: "Human Dev & Family Sci",
  HISP: "Hispanic Studies",
  HIST: "History",
  HLTH: "Health",
  HMGT: "Hosp, Hotel Mgmt, Tour",
  HONR: "Honors",
  HORT: "Horticultural Sciences",
  IBST: "Institute Biosci & Tech",
  IBUS: "International Business",
  IDIS: "Industrial Distribution",
  INST: "Interdisciplinary Studies",
  INTA: "International Affairs",
  ISEN: "Indust & Systems Engr",
  ISTM: "Mgmt Info Systems",
  ITAL: "Italian",
  ITDE: "Interdisciplinary Engr",
  ITSV: "Info Tech Service Mgmt",
  JAPN: "Japanese",
  JOUR: "Journalism",
  JWST: "Jewish Studies",
  KINE: "Kinesiology",
  LAND: "Landscape Architecture",
  LAW: "Law",
  LDEV: "Land Development",
  LDTC: "Learning Design & Techn",
  LING: "Linguistics",
  LMAS: "Latino/Mex Amer Studies",
  LTPS: "Learn Tech & Perf Sys",
  MASC: "Integrated Math & Sci",
  MATH: "Mathematics",
  MCMD: "Molecular Cell Medicine",
  MEEN: "Mechanical Engineering",
  MEFB: "Mid Grds Ed Field Based",
  MEMA: "Mechanics and Materials",
  MEPS: "Molecular & Env Plant Sci",
  MGMT: "Management",
  MKTG: "Marketing",
  MLSC: "Military Science",
  MMET: "Mfg & Mech Engr Tech",
  MODL: "Modern Languages",
  MPHY: "Medical Physiology",
  MPIM: "Microbial Pathogen Imm",
  MSCI: "Medical Sciences",
  MSEN: "Materials Science & Engr",
  MSTC: "Music Technology",
  MTDE: "Multidisciplinary Engr",
  MUSC: "Music",
  MUST: "Museum Studies",
  MXET: "Multidiscip Engr Tech",
  NEXT: "Neuro Exper Therapeutic",
  NRPR: "Nursing Practice",
  NRSC: "Neuroscience",
  NSEB: "Nat'l Student Exch-Home",
  NUEN: "Nuclear Engineering",
  NURS: "Nursing",
  NUTR: "Nutrition",
  NVSC: "Naval Science",
  OBIO: "Oral Biology",
  OCEN: "Ocean Engineering",
  OCNG: "Oceanography",
  OMFP: "Oral & Maxillofac Path",
  OMFR: "Oral & Maxillofac Radio",
  OMFS: "Oral & Maxillofac Surg",
  ORTH: "Orthodontics",
  PBSI: "Psyc & Brain Sciences",
  PEDD: "Pediatric Dentistry",
  PERF: "Performance Studies",
  PERI: "Peridontics",
  PETE: "Petroleum Engineering",
  PHAR: "Pharmacy",
  PHEB: "Public Hlth Epide Biost",
  PHEO: "Public Hlth Enviro Occu",
  PHIL: "Philosophy",
  PHLT: "Public Health",
  PHPM: "Public Hlth Pol & Mgmt",
  PHSC: "Pharmaceutical Sciences",
  PHYS: "Physics",
  PLAN: "Urban Planning",
  PLPA: "Plant Pathology",
  POLS: "Political Science",
  PORT: "Portuguese",
  POSC: "Poultry Science",
  PROS: "Prosthodontics",
  PSAA: "Public Service & Admin",
  PVFA: "Perf Vis Fine Arts",
  RDNG: "Reading",
  RELS: "Religious Studies",
  RUSS: "Russian",
  RWFM: "Rang Wild & Fish Mgmt",
  SABR: "Study Abroad",
  SCMT: "Supply Chain Mgmt",
  SCSC: "Soil and Crop Sciences",
  SEFB: "Special Ed Field Based",
  SENG: "Safety Engineering",
  SOCI: "Sociology",
  SOMS: "Schl of Military Sciences",
  SOPH: "School of Public Health",
  SPAN: "Spanish",
  SPED: "Special Education",
  SPMT: "Sport Management",
  SPSY: "School Psychology",
  SSEN: "Subsea Engineering",
  STAT: "Statistics",
  SYEX: "Second Year Experience",
  TAMU: "Enrollment Type/Holding",
  TCMG: "Technology Management",
  TEED: "Teacher Education",
  TEFB: "Teacher Ed Field Based",
  THEA: "Theatre",
  UGST: "Undergraduate Studies",
  URPN: "Urban & Reg Planning",
  URSC: "Urban Science",
  VIBS: "Vet Integrative Biosci",
  VIST: "Visual Studies",
  VIZA: "Visualization",
  VLCS: "Vet Large Animal Clin Sc",
  VMID: "Vet Medicine-Interdisc",
  VPAR: "Veterinary Parasitology",
  VPAT: "Veterinary Pathology",
  VSCS: "Vet Small Animal Clin Sc",
  VTMI: "Veterinary Microbiology",
  VTPB: "Veterinary Pathobiology",
  VTPP: "Vet Physiology & Pharm",
  WGST: "Women's & Gender Studies",
  WMHS: "Water Mgmt & Hydrol Sci",
} as const;

const ALL_SUBJECTS: TamuSubject[] = Object.entries(TAMU_SUBJECTS).map(([code, name]) => ({
  code: code as TamuSubjectCode,
  name,
}));

export function getTamuSubjectName(code: string): string | undefined {
  const key = code.trim().toUpperCase() as TamuSubjectCode;
  return TAMU_SUBJECTS[key];
}

export function isKnownTamuSubject(code: string): code is TamuSubjectCode {
  return code.trim().toUpperCase() in TAMU_SUBJECTS;
}

export function normalizeSubjectCode(code: string): string {
  return code.trim().toUpperCase().slice(0, 5);
}

/** Match by code prefix or department name keywords. */
export function searchTamuSubjects(query: string, limit = 12): TamuSubject[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];

  const out: TamuSubject[] = [];
  for (const subject of ALL_SUBJECTS) {
    if (subject.code.startsWith(q) || subject.name.toUpperCase().includes(q)) {
      out.push(subject);
      if (out.length >= limit) break;
    }
  }
  return out;
}

export const TAMU_SUBJECT_COUNT = ALL_SUBJECTS.length;
